### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by kim4a** [kim4a/eyes2hex#2]
- [ ] add choices to buttons
- [ ] increase score
- [ ] game over state
- [ ] increase difficulty with each correct answer
